mysite/blog/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^index/$', views.index, name='index'),
    url(r'^user_add/$', views.user_add, name='user_add'),
    # url(r'^ok/$', views.ok, name='ok'),
    url(r'^user_list/$', views.user_list, name='user_list'),
    url(r'^user_info/(\d+)/$', views.user_info, name='user_info'),
    url(r'^del_user/(?P<u_id>\d+)/$', views.del_user, name='del_user'),
    url(r'^update_user/(?P<u_id>\d+)/$', views.update_user, name='update_user'),
    url(r'^user_login/$', views.user_login, name='user_login'),
    url(r'^user_logout/$', views.user_logout, name='user_logout'),
    url(r'^update_self/$', views.update_self, name="update_self"),
    url(r'^update_user_header/(?P<u_id>\d+)/$', views.update_user_header, name="update_user_header"),

    url(r'^code/$', views.code, name='code'),

    # 文章
    url(r'^add_article/$', views.add_article, name='add_article'),
    # url(r'^show_article/$', views.show_article, name='show_article'),
    url(r'^article_content/(\d+)/$', views.article_content, name='article_content'),
    url(r'^article_list/$', views.article_list, name='article_list'),
    url(r'^del_article/(?P<a_id>\d+)/$', views.del_article, name='del_article'),
    url(r'^article_top/(?P<a_id>\d+)/$', views.article_top, name='article_top'),
    url(r'^article_del_top/(?P<a_id>\d+)/$', views.article_del_top, name='article_del_top'),
    url(r'^article_del_res/(?P<a_id>\d+)/$', views.article_del_res, name='article_del_res'),
    url(r'^update_article/(?P<a_id>\d+)/$', views.update_article, name='update_article'),
    url(r'^main/$', views.main, name='main'),
    url(r'^user/(\d+)/$', views.user, name='user'),
    url(r'^yuanchuang/', views.yuanchuang, name='yuanchuang'),
    url(r'^banyun/', views.banyun, name='banyun'),
    url(r'^other/', views.other, name='other'),
    url(r'^del_article_list/', views.del_article_list, name='del_article_list'),


    url(r'^(\w+)/checkusername/$', views.checkusername, name='checkusername'),
    # url(r'^(\w+)/checkpassword/$', views.checkpassword, name='checkpassword'),

]

mysite/mysite/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('blog.urls', namespace='blog')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    # 百度 ueditor 的路由
    url(r'^ueditor/', include('DjangoUeditor.urls')) ,
]

mysite/blog/models.py
from django.db import models

from DjangoUeditor.models import UEditorField



# Create your models here.
class User(models.Model):
    id = models.AutoField(primary_key=True),
    username = models.CharField(max_length=56, verbose_name="用户用户名")
    password = models.CharField(max_length=256, verbose_name="用户密码")
    name = models.CharField(max_length=99, verbose_name="用户姓名")
    age = models.IntegerField(default=19, verbose_name="用户年龄")
    email = models.EmailField(max_length=256, verbose_name="用户邮箱")
    type = models.IntegerField(default=0, verbose_name="用户级别，0普通会员，1超级管理")
    header = models.ImageField(upload_to='static/headers/', default='static/images/headers/default.png', verbose_name="用户头像")
    self_info = models.CharField(max_length=256, default="还没有设置个性签名", verbose_name="用户的个性签名")
    article_num = models.IntegerField(default=0,verbose_name="发表文章的数量")

    def __str__(self):
        return self.username


class Article(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=100, verbose_name="文章标题")
    note = models.CharField(max_length=256, verbose_name="内容摘要")
    # content = models.TextField(verbose_name="文章内容")
    content = UEditorField(verbose_name="文章内容")
    publish_time = models.DateTimeField(auto_now_add=True, verbose_name="发布时间")
    update_time = models.DateTimeField(auto_now=True, verbose_name="修改时间")
    count = models.IntegerField(default=0, verbose_name="点击量")
    image = models.ImageField(upload_to='static/articles/header_image', null=True, verbose_name="文章封面图片")
    # 外键
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    # 文章类型 默认= 1 一般文章，2 置顶文章， 0 隐藏（删除）文章
    type = models.IntegerField(default=1, verbose_name="文章状态")
    # 文章分类 1==搬运 2==原创 3==其它  默认其他
    feilei = models.IntegerField(default=3, verbose_name="文章的分类")

    def __str__(self):
        return self.title

mysite/blog/views.py
from io import BytesIO
import math
from django.shortcuts import render
from django.shortcuts import HttpResponseRedirect
from django.shortcuts import reverse,redirect
from django.http import HttpResponse
from django.db.models import Q
from django.http import JsonResponse
from django.conf import settings
from . import models
from . import utils
from . import cachutils



def index(request):
    # 首页不需改变的直接引用
    articles = cachutils.getAllArticles()
    # 分页  ----第一种方法：手写
    pageNow = int(request.GET.get("pageNow", 1))  # 当前是第几页
    pageSize = int(request.GET.get("pageSize", settings.PAGE_SIZE))   # 一页显示几个
    allCount = len(articles)        # 当前共有多少篇文章
    pageCount = math.ceil(allCount/pageSize)     # 所以文章数量/一页显示几个  向上取整 得到一共有多少页
    #
    page = articles[(pageNow - 1) * pageSize:pageNow * pageSize]   # 从第几个开始取，取几个
    pagerange = range(1, pageCount+1)     # 构造循环器

    # 查到所有文章，按照文章的发布时间倒序排列
    # articles = models.Article.objects.filter(type=1).order_by("-publish_time")


    # print(len(users))
    # print(users)
    # ***********************************************************
    # 查热门文章 安装阅读量倒序排列。进行切片显示8个文章
    h_articles = models.Article.objects.filter(Q(type=1) | Q(type=2)).order_by("-publish_time")
    hot_articles = h_articles.order_by("-count")[0:8]
    # 查所有用户 切片 0:6
    users = models.User.objects.all().order_by("-article_num")[0:6]
    # 置顶文章
    article_top = models.Article.objects.filter(type=2).order_by("-publish_time")

    return render(request, "blog/index.html", {"articles": page,    # 数据库取出来的展示在当前页面的文章
                                               "pagerange": pagerange,    # 一页显示的循环几次
                                               "pageNow": pageNow,  # 当前是第几页
                                               "pageSize": pageSize,    # 一页显示几个
                                               "allCount": allCount,    # 当前一共有多少个文章
                                               "pageCount": pageCount,  # 当前一共有多少页
                                               "hot_articles": hot_articles, "users": users, "article_top": article_top})
    # ***********************************************************

def ok(request):
    return render(request, "blog/ok.html", {})



def user_add(request):
    if request.method == "GET":
        return render(request, 'blog/user_add.html', {})
    if request.method == "POST":
        try:
            username = request.POST['username'].strip()
            password = request.POST['password'].strip()
            password2 = request.POST['password2'].strip()
            # name = request.POST['name'].strip()
            # age = request.POST['age'].strip()
            email = request.POST['email']

            # 获取到用户输入的验证码
            code = request.POST['code']
            # 获取当前的code
            mycode = request.session['code']
            # 判断用户输出的验证码和生成的验证码是否相等
            if code.upper() != mycode.upper() :
                return render(request, 'blog/user_add.html', {"msg": "验证码输入有误，请重新输入注册"})

            # 删除session的验证码
            del request.session['code']

            if len(username) < 1:
                return render(request, 'blog/user_add.html', {"msg": "用户名不能为空"})
            if len(username) > 50:
                return render(request, 'blog/user_add.html', {"msg": "用户名过长"})
            if len(models.User.objects.filter(username=username)):
                return render(request, 'blog/user_add.html', {"msg": "用户名已存在"})

            if len(password) < 6:
                return render(request, 'blog/user_add.html', {"msg": "密码不能小于6位"})
            if password != password2 :
                return render(request, 'blog/user_add.html', {"msg": "两次密码输入不一致"})
            # if int(age) < 0:
            #     return render(request, 'blog/user_add.html', {"msg": "年龄不合法"})
            # if int(age) > 0:
            #     return render(request, 'blog/user_add.html', {"msg": "年龄不合法"})
            # if len(name) < 1:
            #     return render(request, 'blog/user_add.html', {"msg": "姓名不合法"})
            # if len(name) > 10:
            #     return render(request, 'blog/user_add.html', {"msg": "姓名不合法"})


            password = utils.hmac_md5(password)
            user = models.User(username=username, password=password, email=email)
            user.save()
            print("11111")
            # return HttpResponseRedirect("/blog/ok")
            return render(request, "blog/ok.html", {})
        except:
            return render(request, '/blog/user_login.html', {"msg": "很抱歉，注册失败！"})

@utils.require_login
def user_list(request):
    users = models.User.objects.all()
    print(users)
    return render(request, 'blog/user_list.html', {"users": users})


@utils.require_login
def user_info(request, u_id):
    user = models.User.objects.get(pk=u_id)
    print(user)
    return render(request, "blog/user_info.html", {"user": user})


@utils.require_login
def del_user(request,u_id):
    user = models.User.objects.get(pk=u_id)
    article = models.Article.objects.get(author_id =u_id)
    # article.type = 0
    # article.save()
    article.delete()
    print(user)
    user.delete()
    return HttpResponseRedirect("/blog/user_list")


@utils.require_login
def update_user(request, u_id):
    user = models.User.objects.get(id=u_id)
    if request.method == "GET":
        return render(request, "blog/update_user.html", {"user": user})
    if request.method == "POST":
        username = request.POST['username']
        age = request.POST['age']
        email = request.POST['email']
        self_info = request.POST['self_info']

        user.username = username
        user.age = age
        user.email = email
        user.self_info = self_info
        print("111")
        user.save()
        print("222")

        return redirect("/blog/user_info/" + str(u_id) + "/")


@utils.require_login
def update_user_header(request, u_id):
    print("开始执行函数")
    user = models.User.objects.get(id=u_id)
    print("获取到用户了")
    header = request.FILES.get('header', 'static/images/headers/default.png')
    print("获取到头像了")
    print(header)
    user.header = header
    user.save()
    print("保存了")
    print(header)
    request.session["LoginUser"] = user
    print("更新了session")
    return redirect("/blog/user_info/" + str(u_id) + "/")


def user_login(request):
    if request.method == "GET":
        return render(request, 'blog/user_login.html', {"msg": "认真填写哟~"})
    elif request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        print(username + password)

        # 获取到用户输入的验证码
        code1 = request.POST['code']
        # 获取当前的code
        mycode1 = request.session['code']
        # 判断用户输出的验证码和生成的验证码是否相等
        if code1.upper() != mycode1.upper():
            return render(request, 'blog/user_login.html', {"msg": "验证码输入有误，请重新登录"})

        # 删除session的验证码
        del request.session['code']

        password = utils.hmac_md5(password)

        try:
            user = models.User.objects.get(username=username, password=password)
            # filter 用len(user)判断长度是否登录成功
            print("登录成功")
            request.session["LoginUser"] = user
            return redirect(reverse("blog:main"))
            # return reverse("blog:index")

        except:
            return render(request, "blog/user_login.html", {"msg": "账号或密码错误，请重新登录"})

        # 用filter 查询，用len()判断多少个
        # print("1")
        # user = models.User.objects.filter(username=username, password=password)
        # print("2")
        # print(user)
        # if len(user) > 0:
        #     return render(request, 'blog/index.html', {})
        # else:
        #     return render(request, 'blog/user_login.html', {})

# 文章


@utils.require_login
def add_article(request):
    if request.method == 'GET':
        return render(request, "blog/add_article.html", {})

    elif request.method == 'POST':
        title = request.POST['title']
        content = request.POST['content']
        note = request.POST['note']
        author = request.session['LoginUser']
        feilei = request.POST['feilei']
        if len(note) < 1:
            print("a")
            note = utils.clear_html(content)
            note = note[:80]
            print("========")
            print(note)
            print("==============")

        # return
        print(title, content, note, author, feilei)
        try:
            # headers = request.FILES.get('headers', 'static/images/headers/default.png')
            image = request.FILES.get('image')
            print("****")
            print(image)
            print("*********")
            articles = models.Article.objects.filter(Q(author_id=author.id) & Q(Q(type=1) | Q(type=2)))
            article_num = len(articles)
            article_num += 1

            article = models.Article(title=title, content= content, note= note, author= author, image=image, feilei=feilei)
            article.save()

            user = models.User.objects.get(id=author.id)
            user.article_num = article_num
            print(article_num)
            user.save()


            # 添加文章保存缓存一下下
            cachutils.getAllArticles(ischange=True)

            # return render(request, "blog/index.html", {})
            return redirect(reverse("blog:index"))
            # return JsonResponse({"msg":"成功", "success": True})
        except:
            articles = models.Article.objects.filter(Q(author_id=author.id) & Q(Q(type=1) | Q(type=2)))
            article_num = len(articles)
            article_num += 1
            return
            article = models.Article(title=title, content=content, note=note, author=author, feilei=feilei)
            article.save()
            user = models.User.objects.get(id=author.id)
            user.article_num = article_num
            print(article_num)
            user.save()


            # return render(request, "blog/index.html", {})
            return redirect(reverse("blog:index"))


@utils.require_login

mysite/blog/templates/blog/index.html
{% extends 'base.html' %}
{% block con_left %}

{% for a_t in article_top %}
<div class="media wz">

  <div class="media-body">
    <a href="/blog/article_content/{{a_t.id}}" class="media-heading wz-title"><strong>{{a_t.title | truncatechars:30 }}</strong></a>
    <span class="label label-danger">置顶</span>
    <p class="text-left text-muted" >
        {{a.note|truncatechars:80}}
    </p>
  </div>
    {% if a_t.image %}
    <div class="media-right media-middle">
        {% load static %}
    <a href="/blog/article_content/{{a_t.id}}">
      <!--<img class="media-object" src="{% static 'images/wz/1.jpg' %}" alt="...">-->
      <img class="media-object" src="/static/uepload/{{a_t.image}}" alt="...">
    </a>
  </div>
    {% else %}
    {% endif %}
    <div class="media-bottom">
        <p class="text-muted text-left">
        <a href="/blog/user/{{a_t.author_id}}"><span  id="author">{{a_t.author.username}}</span></a>
        <span class="glyphicon glyphicon-eye-open" id="yd"></span> {{a_t.count}}
        <a href="" id="pl-link"><span class="glyphicon glyphicon-comment" id="pl"></span> 99</a>
        <span  id="time">{{a_t.publish_time}}</span>
        </p>
    </div>
</div>


    {% endfor %}



<!--==================================================-->

{% for a in articles %}
<div class="media wz">

  <div class="media-body">
    <a href="/blog/article_content/{{a.id}}" class="media-heading wz-title"><strong>{{a.title | truncatechars:25 }}</strong></a>
    <span class="label label-default">文章</span>
    <p class="text-left text-muted" >
        {{a.note|truncatechars:75}}
    </p>
  </div>
    {% if a.image %}
    <div class="media-right media-middle">
        {% load static %}
    <a href="/blog/article_content/{{a.id}}">
      <!--<img class="media-object" src="{% static 'images/wz/1.jpg' %}" alt="...">-->
      <img class="media-object" src="/static/uepload/{{a.image}}" alt="...">
    </a>
  </div>
    {% else %}
    {% endif %}
    <div class="media-bottom">
        <p class="text-muted text-left">
        <a href="/blog/user/{{a.author_id}}"><span  id="author">{{a.author.username}}</span></a>
        <span class="glyphicon glyphicon-eye-open" id="yd"></span> {{a.count}}
        <a href="" id="pl-link"><span class="glyphicon glyphicon-comment" id="pl"></span> 99</a>
        <span  id="time">{{a.publish_time}}</span>
        {% if a.feilei == 3 %}
            <a href="{% url 'blog:other' %}" id="time" style="color: #567;" title="所属栏目">其它专栏</a>
        {% elif a.feilei == 2 %}
            <a href="{% url 'blog:yuanchuang' %}" id="time" style="color: #567;" title="所属栏目">原创专栏</a>
        {% elif a.feilei == 1 %}
            <a href="{% url 'blog:banyun' %}" id="time" style="color: #567;" title="所属栏目">搬运专栏</a>
        {% endif %}
        </p>
    </div>
</div>


    {% endfor %}
<div class="row col-md-8 col-md-offset-3">
    <nav aria-label="Page navigation">
      <ul class="pagination">
          <li>
              <a href="/blog/index/?pageNow=1" aria-label="Previous" title="首页">
                <span aria-hidden="true">&laquo;</span>
              </a>
            </li>

          {% if pageNow > 1 %}
          <li>
              <a href="/blog/index/?pageNow={{pageNow|add:-1}}" title="上一页">
                  上一页
              </a>
          </li>
          {% endif %}

          {% for page in pagerange %}
              {% if page == pageNow %}
                <li class="active">
                    <a href="/blog/index/?pageNow={{page}}" title="当前页面">
                        {{page}}
                    </a>
                </li>

              {% elif page >= pageNow|add:'-2' and page <= pageNow|add:'2' %}
                <li>
                    <a href="/blog/index/?pageNow={{page}}" title="第{{page}}页">
                        {{page}}
                    </a>
                </li>
              {% endif %}
          {% endfor %}
          {% if pageNow < pageCount %}
          <li>
              <a href="/blog/index/?pageNow={{pageNow|add:1}}" title="下一页">
                  下一页
              </a>
          </li>
          {% endif %}
          <li>
              <a href="/blog/index/?pageNow={{pageCount}}" aria-label="Next" title="尾页">
                <span aria-hidden="true">&raquo;</span>
              </a>
            </li>
      </ul>
    </nav>
</div>
{% endblock %}

<!--========================================-->

{% block hot_articles %}
<ul class="list-group hot-wz">
    <li class="list-group-item" id="hot-wz-title">
        <h4><span class="glyphicon glyphicon-folder-open"></span> &nbsp;热门文章</h4>
    </li>
    {% for h_a in hot_articles %}
    <li class="list-group-item"><a href="/blog/article_content/{{h_a.id}}">{{h_a.title | truncatechars:28 }}</a></li>

    {% empty %}
    <li class="list-group-item"><a href="">还没有热门文章！</a></li>
    {% endfor %}

</ul>
{% endblock %}
{% block hot_user %}

<ul class="list-group hot-yh">
			  <li class="list-group-item" id="hot-yh-title">
			    <h4><i class="glyphicon glyphicon-education"></i> &nbsp;热门用户</h4>
			  </li>
            {% for user in users %}
			  <li class="list-group-item">
			  	<a href="/blog/user/{{user.id}}">
			  		<img src="/static/uepload/{{user.header}}">
			  		<span>{{user.username}}</span>
			  	</a>
			  </li>
    {% empty %}
    <h3>暂时没有用户</h3>
    {% endfor %}
			</ul>

{% endblock %}

{% block music %}
{% endblock %}

mysite/blog/templates/blog/user_add.html
{% extends 'base.html' %}
{% block title %}用户注册{% endblock %}
{% block baner %}

{% endblock %}

{% block main %}
<div class="col-md-8 col-md-offset-2">

    <!-- 注册弹出层 -->

    <div class="reg">

        <div class="info">{{msg}}</div>
        <form class="form-horizontal" method="post" action="/blog/user_add/">
            {% csrf_token %}
            <div class="form-group">
                <label for="username" class="col-sm-2 control-label">账 号：</label>
                <div class="col-sm-8" id="uname">
                    <input type="text" autocomplete="off" class="form-control" id="username" placeholder="请输入注册昵称(用于登录账号)" name="username"
                           required>
                </div>
                <div class="col-md-2" id="msg"></div>
            </div>

            <div class="form-group">
                <label for="password" class="col-sm-2 control-label">密 码：</label>
                <div class="col-sm-8" id="pwd">
                    <input type="password" class="form-control" id="password" placeholder="请输入注册密码" name="password"
                           required>
                </div>
                <div class="col-md-2" id="pmsg"></div>
            </div>

            <div class="form-group">
                <label for="password2" class="col-sm-2 control-label">确认密码：</label>
                <div class="col-sm-8" id="pwd2">
                    <input type="password" class="form-control" id="password2" placeholder="请确认注册密码" name="password2"
                           required>
                </div>
                <div class="col-md-2" id="pmsg2"></div>
            </div>

            <!--<div class="form-group">-->
                <!--<label for="name" class="col-sm-2 control-label">姓名：</label>-->
                <!--<div class="col-sm-8">-->
                    <!--<input type="text" autocomplete="off" class="form-control" id="name" placeholder="请输入真实姓名" name="name" required>-->
                <!--</div>-->
                <!--<div class="col-md-2"></div>-->
            <!--</div>-->

            <!--<div class="form-group">-->
                <!--<label for="age" class="col-sm-2 control-label">年龄：</label>-->
                <!--<div class="col-sm-8" id="agebox">-->
                    <!--<input type="number" autocomplete="off" class="form-control" id="age" placeholder="请输入年龄(只能为数字)" name="age" required>-->
                <!--</div>-->
                <!--<div class="col-md-2" id="agemsg"></div>-->
            <!--</div>-->

            <div class="form-group">
                <label for="email" class="col-md-2 control-label">邮箱：</label>
                <div class="col-md-8">
                    <input type="email" autocomplete="off" class="form-control" id="email" placeholder="请输入联系邮箱" name="email" required>
                </div>
                <div class="col-md-2"></div>
            </div>

            <div class="form-group">
                <label for="yzm" class="col-md-2 control-label">验证码：</label>
                <div class="col-md-4">
                    <input type="text" autocomplete="off" id="yzm" class="form-control"  placeholder="请输入验证码" name="code" required>
                </div>
                <div class="col-md-4">
                    <a onclick="changeCode()" href="javascript:void(0)"><img id="code" src="{% url 'blog:code' %}" alt="验证码" title="点击刷新验证码"></a>
                </div>
                <!--<div class="col-md-2">-->
                    <!--<a onclick="changeCode()" href="javascript:void(0)">点击刷新验证码</a>-->
                <!--</div>-->
                <div class="col-md-2"></div>
            </div>

            <input type="submit" value="注册" id="sub_btn" class="btn btn-success col-md-10 col-md-offset-1 "disabled>
        </form>
    </div>

</div>
</div>
<script>
        function changeCode() {
//            document.getElementById("code").src = "/blog/code?id="+ new Date().getTime()
            document.getElementById("code").src = "/blog/code?id="+ Math.random()
        }

        // 验证用户名
        $(function () {
            $("#username").on("blur",function () {
                console.log("abc")
                uname = $("#username").val()
                console.log(uname)
                $.ajax({
                    url:"/blog/"+uname+"/checkusername/",
                    method:"POST",
                    dataType:"json",
                    data:{"csrfmiddlewaretoken":"{{ csrf_token }}"},
                    success:function (data) {
                        console.log(data)
                        if (data.success){
                            // $("#uname").addClass("has-success")
                            $("#msg").html("<span style='color:green;'>"+data.msg+"</span>")
                        }else{
                            // $("#uname").addClass("has-error")
                            $("#sub_btn").attr("disabled",true)
                            $("#msg").html("<span style='color:red;font-size: 12px;line-height: 5px;'>"+ data.msg + "</span>")
                        }
                    }
                })
            })

            // 验证密码
            $(function () {
            $("#password").on("blur",function () {
                console.log("abc")
                password = $("#password").val()
                console.log(password.length)
                if (password.length < 6){
                    // $("#pwb").addClass("has-error")
                    $("#sub_btn").attr("disabled",true)
                    $("#pmsg").html("<span style='color:red;'>"+"密码长度不足6位"+"</span>")
                }else {
                    // $("#pwb").addClass("has-success")

                    $("#pmsg").html("<span style='color:green;'>"+"密码合法！！请继续输入" + "</span>")
                }
                })
            })

            // 第二次密码验证
            $(function () {
            $("#password2").on("blur",function () {
                console.log("abc")
                password2 = $("#password2").val()
                console.log(password2.length)
                if (password2 != password){
                    // $("#pwb2").addClass("has-error")
                    $("#sub_btn").attr("disabled",true)
                    $("#pmsg2").html("<span style='color:red;'>"+"两次密码不一致"+"</span>")
                }else {
                    // $("#pwb2").addClass("has-success")
                    $("#sub_btn").removeAttr("disabled")
                    $("#pmsg2").html("<span style='color:green;'>"+"密码合法！！请继续输入" + "</span>")
                }
                })
            })

            //年龄验证
            $(function () {
                $("#age").on("blur",function () {
                    console.log("输入年龄了")
                    age = $("#age").val()
                    console.log(age)
                    if (age >= 1){
                        // $("#agebox").addClass("has-success")
                        $("#sub_btn").removeAttr("disabled")
                        $("#agemsg").html("<span style='color:green;'>"+"年龄合法！！请继续输入" + "</span>")
                    }else{
                        // $("#agebox").addClass("has-error")
                        $("#sub_btn").attr("disabled",true)
                        $("#agemsg").html("<span style='color:red;'>"+"请认真填写年龄"+"</span>")
                    }
                })
            })

            //验证码验证
            // $(function () {
            //     $("#yzm").on("blur",function () {
            //         console.log("输入过验证码了")
            //         yzm = $("#yzm").val()
            //         console.log(yzm)
            //        if (yzm.length > 0):
            //         return
            //     })
            // })

        })
    </script>
{% endblock %}

{% block music %}
{% endblock %}

mysite/blog/templates/blog/user_login.html
{% extends 'base.html' %}
{% block title %}用户登录{% endblock %}
{% block baner %}
{% endblock %}

{% block main %}

<div class="col-md-8 col-md-offset-2">
    <div class="reg">
        <div class="info">{{msg}}</div>
        <form class="form-horizontal" action="/blog/user_login/" method="post">
            {% csrf_token %}

            <div class="form-group">
                <label for="username" class="col-md-2 control-label">昵称：</label>
                <div class="col-md-10">
                    <input type="text" autocomplete="off" class="form-control" id="username" placeholder="请输入昵称" name="username" required>
                </div>
            </div>

            <div class="form-group" style="margin-top: 5%;margin-bottom: 8%;">
                <label for="password" class="col-md-2 control-label">密码：</label>
                <div class="col-md-10">
                    <input type="password" class="form-control" id="password" placeholder="请输入密码" name="password" required>
                </div>
            </div>

            <div class="form-group">
                <label for="code" class="col-md-2 control-label">验证码：</label>
                <div class="col-md-4">
                    <input type="text" autocomplete="off" class="form-control"  placeholder="请输入验证码" name="code" required>
                </div>
                <div class="col-md-3">
                    <a onclick="changeCode()" href="javascript:void(0)"><img id="code" src="{% url 'blog:code' %}" alt="验证码" title="点击刷新验证码"></a>
                </div>
                <div class="col-md-3">
                    <a onclick="changeCode()" href="javascript:void(0)">点击刷新验证码</a>
                </div>
            </div>
            <input type="submit" value="登录" class="btn btn-success col-md-10 col-md-offset-1">
        </form>
    </div>
</div>
</div>

{% endblock %}

{% block music %}
{% endblock %}